### -*-Makefile-*- pour préparer "Méthodes numériques en actuariat
###                avec R"
##
## Copyright (C) 2018 Vincent Goulet
##
## Ce fichier est seulement là pour permettre de démarrer la
## compilation du projet depuis le répertoire courant.
##
## 'make pdf' crée les fichiers .tex à partir des fichiers .Rnw avec
## Sweave et compile le document maître avec XeLaTeX.
##
## 'make all' est équivalent à 'make pdf'.
##
## Auteur: Vincent Goulet
##
## Ce fichier fait partie du projet
## "Méthodes numériques en actuariat avec R"
## https://github.com/vigou3/methodes-numeriques-en-actuariat

all: pdf

.PHONY: pdf

pdf:
	${MAKE} pdf -C ..
